/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package P4P;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import java.awt.Toolkit;
import java.awt.Image;


/**
 *
 * @author benam
 */
public class SaisieJoueurDlg extends javax.swing.JDialog {

    /**
     * Creates new form SaisieJoueurDlg
     */
    private Joueur j1;
    private boolean ok;
    private ImageIcon photo;
    private LesJoueurs lj;
    private BoutonImage bt;
    
    public SaisieJoueurDlg(java.awt.Frame parent, boolean modal, LesJoueurs lj) {
        super(parent, modal);
        initComponents();
        this.ok=false;
        this.photo=null;
        this.j1=null;
        this.lj=lj;
        this.bt=new BoutonImage();
        bt.setIcon(new ImageIcon(getClass().getResource("/tp3/img/joueurDefaut.png")));
        jPanel2.add(bt);
        this.pack();
        this.setSize(500, 400);

    }
    public boolean getok(){
        return this.ok;
    }
    public Joueur getjoueur(){
        return this.j1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pseudo = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        parcourir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        valide = new javax.swing.JButton();
        annuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setLayout(new java.awt.GridLayout(2, 2));

        jLabel2.setText("Pseudo ?");
        jPanel2.add(jLabel2);

        pseudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pseudoActionPerformed(evt);
            }
        });
        jPanel2.add(pseudo);

        jPanel4.setLayout(new java.awt.GridLayout(1, 2));

        jLabel3.setText("Photo ?");
        jPanel4.add(jLabel3);

        parcourir.setText("Parcourir");
        parcourir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parcourirActionPerformed(evt);
            }
        });
        jPanel4.add(parcourir);

        jPanel2.add(jPanel4);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Ajout d'un nouveau joueur");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        valide.setText("Valider");
        valide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valideActionPerformed(evt);
            }
        });
        jPanel3.add(valide);

        annuler.setText("Annuler");
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });
        jPanel3.add(annuler);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pseudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pseudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pseudoActionPerformed

    private void parcourirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parcourirActionPerformed
        // TODO add your handling code here:
        JFileChooser jf= new JFileChooser("./src/tp3/img/"); //recupere le fichier dans le dossier source
        if (jf.showOpenDialog(this)== JFileChooser.APPROVE_OPTION){
            String path = jf.getSelectedFile().getPath();
            Image img=Toolkit.getDefaultToolkit().getImage(path);
            img=img.getScaledInstance(bt.getWidth()-10, bt.getHeight()-10, Image.SCALE_DEFAULT);
            this.photo = new ImageIcon(img);
            bt.setIcon(photo);
        } 
    }//GEN-LAST:event_parcourirActionPerformed

    private void valideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valideActionPerformed
        // TODO add your handling code here:
        if(!pseudo.getText().trim().isEmpty())//verifie les esapce avant et apres et regarde sur le jetextfiel n'est pas vide
        {
            this.j1=new Joueur(pseudo.getText());
            this.j1.setPhoto(this.photo);
            lj.ajoutej(j1);
            this.ok=true;
            this.setVisible(false);
            this.dispose();
        }
        else 
            pseudo.setText("Erreur renseignement");
    }//GEN-LAST:event_valideActionPerformed

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        // TODO add your handling code here:
        this.ok=false;
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_annulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LesJoueurs lj =new LesJoueurs();
                SaisieJoueurDlg dialog = new SaisieJoueurDlg(new javax.swing.JFrame(), true,lj);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annuler;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton parcourir;
    private javax.swing.JTextField pseudo;
    private javax.swing.JButton valide;
    // End of variables declaration//GEN-END:variables
}
