/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package P4P;
import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author benam
 */
public class SelectionJoueursDlg extends javax.swing.JDialog {

    /**
     * Creates new form SelectionJoueursDlg
     */
    private Joueur j1;
    private Joueur j2;
    private LesJoueurs lj;
    private boolean ok;
    private DefaultListModel<String> modeljdispo;
    private DefaultListModel<String> modelj;
    
    public SelectionJoueursDlg(java.awt.Frame parent, boolean modal,LesJoueurs lj) {
        super(parent, modal);
        initComponents();
        this.j1=null;
        this.j2=null;
        this.lj=lj;
        this.modeljdispo=new DefaultListModel<>();
        this.modelj=new DefaultListModel<>();
        initListesJ();
        this.ok=false;   
    }
    
    public Joueur getJoueur1(){
        return this.j1;
    } 
    
    public Joueur getJoueur2(){
        return this.j2;
    } 
    
    public boolean getOk(){  
       return this.ok;
    } 
 
    private void initListesJ(){
        for(int i=0;i<this.lj.getNbJoueurs();i++){
            this.modeljdispo.addElement(this.lj.getj(i).getPseudo());
        }
        LJoueursDispo.setModel(modeljdispo);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        Bvalider = new javax.swing.JButton();
        Bannuler = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LJoueursDispo = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        Bajoute = new javax.swing.JButton();
        Bretrait = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Ljoueurs = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Bvalider.setText("Valider");
        Bvalider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BvaliderActionPerformed(evt);
            }
        });
        jPanel3.add(Bvalider);

        Bannuler.setText("Annuler");
        Bannuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BannulerActionPerformed(evt);
            }
        });
        jPanel3.add(Bannuler);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane1.setViewportView(LJoueursDispo);

        jPanel2.add(jScrollPane1);

        jPanel4.setLayout(new java.awt.GridLayout(4, 1));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel6);

        Bajoute.setText("===>");
        Bajoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BajouteActionPerformed(evt);
            }
        });
        jPanel4.add(Bajoute);

        Bretrait.setText("<===");
        Bretrait.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BretraitActionPerformed(evt);
            }
        });
        jPanel4.add(Bretrait);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5);

        jPanel2.add(jPanel4);

        jScrollPane2.setViewportView(Ljoueurs);

        jPanel2.add(jScrollPane2);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Sélection des deux joueurs");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BajouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BajouteActionPerformed
        // TODO add your handling code here:
        int index=LJoueursDispo.getSelectedIndex();
        if(index!=-1){
            String j=LJoueursDispo.getSelectedValue();
            modeljdispo.remove(index);
            modelj.addElement(j);//met dans le model le pseudo selectionner
            Ljoueurs.setModel(modelj);//met dans la jliste le model qui contient le pseudo
        }
    }//GEN-LAST:event_BajouteActionPerformed

    private void BretraitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BretraitActionPerformed
        // TODO add your handling code here:
        int index=Ljoueurs.getSelectedIndex();
        if(index!=-1){
            String j=Ljoueurs.getSelectedValue();
            modelj.remove(index);
            modeljdispo.addElement(j);   
        }
    }//GEN-LAST:event_BretraitActionPerformed

    private void BvaliderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BvaliderActionPerformed
        // TODO add your handling code here:
        if(Ljoueurs.getModel().getSize()==2){
            this.j1=lj.rechj(Ljoueurs.getModel().getElementAt(0));//recupere le pseudo puis le joueur 1 et l'affecte a la variable j1
            this.j2=lj.rechj(Ljoueurs.getModel().getElementAt(1));//recupere le pseudo puis le joueur 2 et l'affecte a la variable j2
            this.ok=true;
            this.setVisible(false);
            this.dispose();
        }
    }//GEN-LAST:event_BvaliderActionPerformed

    private void BannulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BannulerActionPerformed
        // TODO add your handling code here:
        this.ok=true;
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BannulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectionJoueursDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectionJoueursDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectionJoueursDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectionJoueursDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LesJoueurs lj =new LesJoueurs();
                Joueur p1 = new Joueur();
                Joueur p2 = new Joueur();
                lj.ajoutej(p1);
                lj.ajoutej(p2);
                SelectionJoueursDlg dialog = new SelectionJoueursDlg(new javax.swing.JFrame(), true ,lj);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bajoute;
    private javax.swing.JButton Bannuler;
    private javax.swing.JButton Bretrait;
    private javax.swing.JButton Bvalider;
    private javax.swing.JList<String> LJoueursDispo;
    private javax.swing.JList<String> Ljoueurs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
