/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package P4P;

import P4P.BoutonImage;
import P4P.Joueur;
import P4P.LesJoueurs;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;

/**
 *
 * @author benam
 */
public class VisuJoueursDlg extends javax.swing.JDialog {
    private final LesJoueurs lj;
    private final DefaultComboBoxModel<String> modelcombo;
    private final BoutonImage bt;
    /**
     * Creates new form VisuJoueurDlgTP
     * @param parent
     * @param modal
     * @param lst
     */
    public VisuJoueursDlg(java.awt.Frame parent, boolean modal,LesJoueurs lst) {
        super(parent, modal);
        initComponents();
        this.pack();
        this.setSize(500,500);
        this.lj=lst;
        this.modelcombo=new DefaultComboBoxModel<>();
        initcombobox();
        this.bt=new BoutonImage();
        bt.setIcon(new ImageIcon(getClass().getResource("/tp3/img/joueurDefaut.png")));
        jPanel1.add(bt);
    }
    public void initcombobox() {
    for (int i=0;i<this.lj.getNbJoueurs(); i++){
        Joueur joueur = lj.getj(i);//Récupère chaque joueur à l'indice i
        this.modelcombo.addElement(joueur.getPseudo());//ajoute le pseudo du joueur au modèle
    }
    jcombo.setModel(this.modelcombo);
    this.modelcombo.setSelectedItem("Joueurs");
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcombo = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jo = new javax.swing.JPanel();
        pseudo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        niveau = new javax.swing.JPanel();
        niv = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edition = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Joueur à visualiser");
        jPanel3.add(jLabel1);

        jcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Joueurs" }));
        jcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboActionPerformed(evt);
            }
        });
        jPanel3.add(jcombo);

        getContentPane().add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jPanel4.setLayout(new java.awt.GridLayout(2, 2));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Pseudo :");
        jPanel4.add(jLabel2);

        jo.setLayout(new java.awt.BorderLayout());

        pseudo.setText("jLabel4");
        jo.add(pseudo, java.awt.BorderLayout.CENTER);

        jPanel4.add(jo);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Niveau :");
        jPanel4.add(jLabel3);

        niveau.setLayout(new java.awt.BorderLayout());

        niv.setText("jLabel5");
        niveau.add(niv, java.awt.BorderLayout.CENTER);

        jPanel4.add(niveau);

        jPanel1.add(jPanel4);

        jPanel2.add(jPanel1);

        edition.setColumns(20);
        edition.setRows(5);
        jScrollPane1.setViewportView(edition);

        jPanel2.add(jScrollPane1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboActionPerformed
        // TODO add your handling code here:
        int index=jcombo.getSelectedIndex();
        if(index!=-1){
            Joueur j=lj.getj(index);
            bt.setIcon(j.getPhoto());
            pseudo.setText(j.getPseudo());
            String c ="";
            niv.setText(c+=j.getNiveau());
            edition.setText(j.toString());
        }
    }//GEN-LAST:event_jcomboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisuJoueursDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisuJoueursDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisuJoueursDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisuJoueursDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                LesJoueurs lst =new LesJoueurs();
                VisuJoueursDlg dialog = new VisuJoueursDlg(new javax.swing.JFrame(), true,lst);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea edition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcombo;
    private javax.swing.JPanel jo;
    private javax.swing.JLabel niv;
    private javax.swing.JPanel niveau;
    private javax.swing.JLabel pseudo;
    // End of variables declaration//GEN-END:variables
}
